services:
    database:
        image: postgres:16-alpine
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
            interval: 5s
            timeout: 3s
            retries: 5
        networks:
            - external
        ports:
            - "5432:5432"
        volumes:
            - db-data:/var/lib/postgresql/data

    redis:
        image: redis:8.4-alpine
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "redis-cli", "ping"]
            interval: 5s
            timeout: 3s
            retries: 5
        networks:
            - external
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data

    shortener:
        build:
            context: ./Shortener/
            dockerfile: ./Dockerfile
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 30s
        env_file:
            - .env
        environment:
            - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
            - ASPNETCORE_URLS=http://*:5000
            - ConnectionStrings__DATABASE=Host=${DB_HOST};Port=${DB_PORT};Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
            - ConnectionStrings__REDIS=${REDIS_HOST}:${REDIS_PORT}
        depends_on:
            database:
                condition: service_healthy
            redis:
                condition: service_healthy
        networks:
            - external
        ports:
            - "5000:5000"

    nginx:
        image: nginx:stable-alpine
        restart: unless-stopped
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./Frontend:/frontend:ro
        depends_on:
            - shortener
        networks:
            - external
        ports:
            - "80:80"
            - "443:443"

    seq:
        image: datalust/seq:latest
        restart: unless-stopped
        environment:
            - ACCEPT_EULA=Y
            - SEQ_FIRSTRUN_ADMINPASSWORD=admin123
        volumes:
            - seq-data:/data
        networks:
            - external
        ports:
            - "5341:5341"
            - "8081:80"

networks:
    external:
        driver: bridge

volumes:
    db-data:
    redis-data:
    seq-data:
