services:
    database:
        image: postgres:16-alpine
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
            interval: 5s
            timeout: 3s
            retries: 5
        networks:
            - internal
            - external
        ports:
            - "${DB_EXTERNAL_PORT}:5432"
        volumes:
            - db-data:/var/lib/postgresql/data

    redis:
        image: redis:8.4-alpine
        healthcheck:
            test: ["CMD-SHELL", "redis-cli", "-a", "ping"]
            interval: 5s
            timeout: 3s
            retries: 5
        networks:
            - internal
            - external
        ports:
            - "${REDIS_EXTERNAL_PORT}:6379"
        volumes:
            - redis-data:/data

    shortener:
        build:
            context: ./Shortener/
            dockerfile: ./Dockerfile
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:${BACKEND_PORT}/health"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 10s
        env_file:
            - .env
        environment:
            - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
            - ASPNETCORE_URLS=http://*:${BACKEND_PORT}
            - ConnectionStrings__DATABASE=Host=${DB_HOST};Port=${DB_PORT};Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
            - ConnectionStrings__REDIS=${REDIS_HOST}:${REDIS_PORT}
        depends_on:
            database:
                condition: service_healthy
            redis:
                condition: service_healthy
        networks:
            - internal
            - external
        ports:
            - "${BACKEND_PORT}:${BACKEND_PORT}"

    nginx:
        image: nginx:stable-alpine
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./Frontend:/frontend:ro
        depends_on:
            - shortener
        networks:
            - internal
            - external
        ports:
            - 80:80
            - 443:443

    seq:
        image: datalust/seq:latest
        environment:
            - ACCEPT_EULA=Y
            - SEQ_FIRSTRUN_ADMINPASSWORD=admin123
        volumes:
            - seq-data:/data
        networks:
            - internal
            - external
        ports:
            - 5341:5341
            - 8081:80

networks:
    internal:
        driver: bridge
        internal: true
    external:
        driver: bridge

volumes:
    db-data:
    redis-data:
    seq-data: