user root;
worker_processes 1;

events {
}

http {
    include mime.types;
    sendfile on;

    server {
        listen 80;
        root /frontend;

        location / {
            try_files $uri $uri.html $uri/index.html =404;
            error_page 404 =404 /not-found.html;
            error_page 500 =500 /error.html
        }

        location /api/ {
            proxy_pass http://shortener:5000/api/;
        }

        location ~ "^/[0-9A-Za-z]{8}$" {
            proxy_pass http://shortener:5000$request_uri;
            proxy_intercept_errors on;
            error_page 404 =404 /not-found.html;
            error_page 500 =500 /error.html
        }
    }
}